---
include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

stages:
  - check

sast:
  stage: check

secret_detection:
  stage: check

OSV scanner:
  image:
    name: golang:latest
  stage: check
  before_script:
    - "go install github.com/google/osv-scanner/cmd/osv-scanner@latest"
  script:
    - 'PATH="${PATH}:$(go env GOPATH)/bin" osv-scanner -r .'
  timeout: 10 minutes

super linter:
  image:
    name: ghcr.io/super-linter/super-linter:v7.3.0@sha256:2049d418092bdc1bba1e4022b2c11bdcfd45092fdfade47877881407893b0a28
    entrypoint:
      - ""
  stage: check
  variables:
    RUN_LOCAL: "true"
    DEFAULT_BRANCH: "main"
    USE_FIND_ALGORITHM: "true"
    VALIDATE_ALL_CODEBASE: "true"
    LINTER_RULES_PATH: "."
    FILTER_REGEX_EXCLUDE: "(.aws/*|.docker/*|.git-credentials|.ssh/*)"
  before_script:
    - 'ln -s "$(pwd)" /tmp/lint'
  script:
    - "/action/lib/linter.sh"
  timeout: 10 minutes
